const TYPES = {
    LOADING_DATA: "LOADING_DATA",
    FETCHING_DATA: "FETCHING_DATA",
    LOADED_DATA_SUCCES: "LOADED_DATA_SUCCES",
    LOADED_DATA_FAILED: "LOADED_DATA_FAILED"
};

export default TYPES;